# ##################################################
# theme-defined params

  # meta data
  # ##############################

  # used in layouts/partials/head.meta.html
  authorName                        = "anonymous"
  defaultKeywords                   = ["foo", "bar"]
  defaultDescription                = "example site created with hugo using theme hugo-theme-w3css-basic"
  truncateSummaryForMetaDescription = 120

  # used in layouts/partials/footer.bottom.html
  bottomLeft  = "Copyright (c) 2019, *lobortis nisl* ut aliquip ex ea commodo consequat"
  bottomRight = 'created with [Hugo](https://gohugo.io) '


  # colors
  # ##############################

  # used in layouts/partials/head.stylesheets.html
  # https://www.w3schools.com/w3css/w3css_color_themes.asp
  # https://www.w3schools.com/w3css/w3css_color_generator.asp
  # Monochromatic Color Schemes
  # set W3.CSS color theme (choose one)
  #w3cssColorTheme = "/css/w3-theme-custom.css"
  #w3cssColorTheme = "/vendor/w3css/4/custom/w3-theme-comet-dc003a.css"
  w3cssColorTheme = "/vendor/w3css/4/custom/w3-theme-comet-00263a.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-amber.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-black.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-brown.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-cyan.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-dark-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-deep-orange.css"
  #w3cssColorTheme = "/vendor/w63css/4/w3-theme-deep-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-indigo.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-khaki.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-lime.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-pink.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-red.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-teal.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-yellow.css"

  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2006-sand-dollar.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2007-chili-pepper.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2008-blue-izis.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2009-mimosa.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2010-turquise.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2011-honeysucle.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2012-tangerine-tango.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2013-emerald.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2014-radiand-orchid.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2015-marsala.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-airy-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-aurora-red.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-bodacious.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-buttercup.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-duster-cedar.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-fiesta.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-green-flash.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-iced-coffe.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-lilac-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-limpet-shell.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-lush-medow.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-peach-echo.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-potters-clay.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-riverside.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-rose-quarts.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-serenity.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-sharkskin.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-snorkel-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-spicy-mustard.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2016-warm-taupe.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-autumn-maple.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-ballet-slipper.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-butterum.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-flame.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-golden-lime.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-greenery.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-grenadine.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-hazelnut.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-island-paradise.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-kale.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-lapis-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-marina.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-navy-peony.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-neutral-gray.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-niagara.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-pale-dogwood.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-pink-yarrow.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-primrose-yellow.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-shaded-spruce.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2017-tawny-port.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-almond-buff.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-almost-mauve.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-arcadia.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-blooming-dahlia.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-ceylon-yellow.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-cherry-tomato.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-chili-oil.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-coconut-milk.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-crocus-petal.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-emperador.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-harbor-mist.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-limelight.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-lime-punch.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-little-boy-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-martini-olive.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-meadowlark.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-meerkat.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-nebulas-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-pink-lavender.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-quetzal-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-quiet-gray.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-red-pear.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-russet-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-sailor-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-sargasso-sea.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-spring-crocus.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-tofu.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-ultra-violet.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-valiant-poppy.css"
  #w3cssColorTheme = "/vendor/w3css/4/color_of_the_year/w3-theme-color-of-year-2018-warm-sand.css"


  # used in layouts/index.html
  colorHtml                             = "w3-theme-d1"
  # used in layouts/partials/*.html
  # {{ default `w3-theme-l3` ($.Site.Param `color404Container`)}}
  # set the actual color (one of the monochromatic color scheme)
  #
  # layouts/partials/header.marquee.html
  colorHeaderMarquee                    = "w3-theme-d1"
#  
# layouts/partials/front.*.html
  colorFrontPhotocardsCard              = "w3-theme-l1"
  colorFrontPhotocardsCardContainer     = "w3-theme-d1"
  colorFrontPhotocardsContainer         = "w3-theme-l1"
  colorFrontPhotocardsCardTooltip       = "w3-theme-d4"
  #
  # layouts/partials/footer.bottom.html
  colorFooterBottomCell                 = "w3-theme-l5"
  #

  # flags used for tracing and html comment output
  #traceFlags       = "html-comment:debug-shortcodes"
  #traceFlags         = "html-comment:debug-partial-resource-image"
  traceFlags         = "html-comment"

  # custom css and custom js
  # this theme comes with the following "empty" files
  #   static/css/custom.css
  #   static/js/custom.bottom.js
  #   static/js/custom.top.js
  # a project can create these in the project dir in order to overwrite them
  # https://gohugo.io/themes/customizing/#override-static-files

  # in addition the following arrays may be files with paths or URLS
  #   custom_css        = [ "css/custom_foo.css", "https://cdnjs.cloudflare.com/ajax/libs/minireset.css/0.0.2/minireset.min.css" ]
  #   custom_js_top     = [ "js/custom_top_bar.js" ]
  #   custom_js_bottom  = [ "js/custom_bottom_foo.js", "https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js" ]
  # used in layouts/partials/head.stylesheets.html
  # used in layouts/partials/scripts.bottom.html
  # used in layouts/partials/scripts.top.html
  custom_css        = [ ]
  custom_js_top     = [ ]
  custom_js_bottom  = [ ]


  # developer stuff
  debug              = false


# ##################################################
# theme sections
# more theme defined params

[favicon]
  # you may want to use https://realfavicongenerator.net to generate your files
  # used in layouts/partials/head.favicon.html
  # relURL is applied to path
  enable                 = true
  path                   = "/images/favicons"
  version                = "a_random_value"
  maskIcon               = "#5bbad5"
  msapplicationTileColor = "#da532c"
  themeColor             = "#ffffff"

[photocards]
  # used in layouts/partials/front.photocards.html
  # enable or disable photocards on frontpage
  # see some examples in 'exampleSite/data/photocards'
  enable        = true
  #resImgCmd     = "Resize"
  #resImgCmdOpt  = "300x"
  #resImgCmd     = "Fit"
  resImgCmd     = "Fill"
  resImgCmdOpt  = "300x200"

[resources]
	# used in layouts/partials/resource.image.html
	defaultResPagePath	= "resources/images"

[marquee]
  # used in layouts/partials/header.marquee.html
  # enable or disable marquee on frontpage
  enable      = true
  # marquee text is placed in directory as:
  file        = ".marquee.md"
